# Generated by Django 5.2.12 on 2026-03-14 18:21

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(max_length=255)),
                ('schema', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricaQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_nulos', models.FloatField()),
                ('taxa_duplicados', models.FloatField()),
                ('quantidade_linhas', models.BigIntegerField()),
                ('ultima_execucao', models.DateTimeField()),
                ('tabela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualidade', to='catalog.tabela')),
            ],
        ),
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_dado', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='catalog.tabela')),
            ],
        ),
    ]
